version: '3'

services:
  nats-server:
    image: nats:latest
    restart: always
    ports:
      - 8222:8222
      # - 4222:4222
      # - 6222:6222
  
  client-gateway:
    container_name: client-gateway-prod
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:4000
    env_file:
    - ./client-gateway/.env
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
  
  auth-ms:
    container_name: auth-ms-prod
    build: 
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: auth-ms-prod
    env_file:
    - ./auth-ms/.env
    environment:
      - PORT=4004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  
  products-ms:
    container_name: products-ms-prod
    build: 
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: products-ms-prod
    env_file:
    - ./products-ms/.env
    environment:
      - NATS_SERVERS=${NATS_SERVERS}

  orders-ms:
    container_name: orders-ms-prod
    build: 
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: orders-ms-prod
    env_file:
    - ./orders-ms/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@orders-db:5432/${POSTGRES_DB}?schema=public
      - NATS_SERVERS=${NATS_SERVERS}
  
  payments-ms:
    container_name: payments-ms-prod
    build: 
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    env_file:
    - ./payments-ms/.env
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

# docker compose -f docker-compose.prod.yml up --build -d