apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-webhook
  name: payments-webhook
spec:
  ports:
  - name: "4003"
    port: 4003
    protocol: TCP
    targetPort: 4003
  selector:
    app: payments-ms
  type: NodePort
status:
  loadBalancer: {}
